baseURL = "https://kirkayak.netlify.app/"
disqusShortname = ""
languageCode = "en-us"
languageName = "En"
paginate = "5"
theme = "KK"
title = "Kırkayak Kültür"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "İletişim"
url = "contact"
weight = 3
[[menu.main]]
name = "Hakkımızda"
url = "about"
weight = 2
[[menu.main]]
name = "Anasayfa"
url = "/"
weight = 1
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Themefisher"
contact_form_action = "mailto:info@kirkayak.org"
copyright = "Theme Designed By [Themefisher](https://themefisher.com/) & Developed By [Gethugothemes](https://gethugothemes.com/) & Webmaster [Murat Kaya](mailto:muratkaya@kirkayak.org)"
description = "Kırkayak Kültür"
logo = "images/logo.png"
search = true
[params.cookies]
enable = true
expire_days = 2
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
